GET http://127.0.0.1:8000/products HTTP/1.1

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNjE2MzEzLCJpYXQiOjE3NTM2MTYwMTMsImp0aSI6Ijg0NmIyM2NjZDEyNzQ1YjM4MDg2Yzk3ZDlhZjRkN2E1IiwidXNlcl9pZCI6IjEifQ.X4FcARGS74wLtP2uLX-3jWhi77t2JzoiygkcP30PG0k

{
    "name": "Table",
    "description": "4 legs it has",
    "price": "3000.50",
    "stock": "34"
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}


###

GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNjE1MTEwLCJpYXQiOjE3NTM2MTQ4MTAsImp0aSI6ImVhMmQ2MDVlOWE2ZDQ3ZmRiMTI3YWU5ZGZhNzViYjJhIiwidXNlcl9pZCI6IjIifQ.FAW75-MiJHZmViHIuwAOr06ct9xEtiukoDtS78C4AMo

###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzcwMTg2NCwiaWF0IjoxNzUzNjE1NDY0LCJqdGkiOiJlYjMxNjljN2NlZWE0NjNlODZhN2I1N2E4OTc0OTRhNiIsInVzZXJfaWQiOiIxIn0.m_btNZ2EZ8GLi918pkvrHRhw7WSkvA1IZxJeabHK9_k"
}




### ProductInfoApiView (RetrieveUpdateDestroyAPIView)

GET http://127.0.0.1:8000/products/5 HTTP/1.1

###

PATCH http://127.0.0.1:8000/products/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNjIxNTU2LCJpYXQiOjE3NTM2MjEyNTYsImp0aSI6IjI5YWUzYTNkMDgwYjRjY2JhNmRkZGUxYTc2NTg1NjIxIiwidXNlcl9pZCI6IjEifQ.W080fhHE7KbTFGv0DO1KFt-r2qcHQIXnkKNqfIADmmc

{
    "name": "testing"
}

###

PUT http://127.0.0.1:8000/products/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNjIxNTU2LCJpYXQiOjE3NTM2MjEyNTYsImp0aSI6IjI5YWUzYTNkMDgwYjRjY2JhNmRkZGUxYTc2NTg1NjIxIiwidXNlcl9pZCI6IjEifQ.W080fhHE7KbTFGv0DO1KFt-r2qcHQIXnkKNqfIADmmc

{
    "name": "Putting test",
    "description": "blah blah blah",
    "price": 44,
    "stock": "3"
}

###

DELETE  http://127.0.0.1:8000/products/1 HTTP/1.1

###

POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNzY2NjMzLCJpYXQiOjE3NTM3NjYzMzMsImp0aSI6IjI3ZWUxZjhkN2VjYTQxOThhNDg4NTU3ZTk5NjZjNDg0IiwidXNlcl9pZCI6IjEifQ.4s1WyNA3nzNc2yX-sFBaDlO_cqyT0pN3GwufwzqUvhQ

{ 
    "user": 1,
    "status": "Pending",
    "items": [
        {
            "product": 2,
            "quantity": 4
        },
        {
            "product": 4,
            "quantity": 1
        }
    ]
}